export const categories = [

    {
        categoryName: 'Home Installations and Maintenance',
        subCatory: [
            { label: "Flooring installation and repair", value: "Flooring installation and repair" },
            { label: "AllRoof repair", value: "AllRoof repair" },
            { label: "Door installation and repair", value: "Door installation and repair" },
            { label: "Wallpaper installation and removal", value: "Wallpaper installation and removal" },
            { label: "Tile installation and repair", value: "Tile installation and repair" },
            { label: "Cabinet installation and repair", value: "Cabinet installation and repair" },
            { label: "Drywall installation and repair", value: "Drywall installation and repair" },
            { label: "TV installation and repair", value: "TV installation and repair" },
            { label: "Satellite and cable installation and repair", value: "Satellite and cable installation and repair" },
            { label: "Generator installation and repair", value: "Generator installation and repair" },
            { label: "Hot tub installation and repair", value: "Hot tub installation and repair" },
            { label: "Water heater installation and repair", value: "Water heater installation and repair" },
            { label: "Water filtration system installation and repair", value: "Water filtration system installation and repair" },
            { label: "Light installation", value: "Light installation" },
            { label: "Furniture removal", value: "Furniture removal" },
            { label: "Smart home installation", value: "Smart home installation" },
            { label: "Furniture assembly", value: "Furniture assembly" },
            { label: "Mounting", value: "Mounting" },
            { label: "Plumbing", value: "Plumbing" },
            { label: "Painting", value: "Painting" },
            { label: "Electrical work / Electrician", value: "Electrical work / Electrician" },
            { label: "Fence installation and repair services", value: "Fence installation and repair services" },
            { label: "Hose installation", value: "Hose installation" },
            { label: "Shed maintenance", value: "Shed maintenance" },
            { label: "IT security gadget and installations", value: "IT security gadget and installations" },

        ]
    },
    {
        categoryName: 'Art and Home Service',
        subCatory: [
            { label: "Carpentry", value: "Carpentry" },
            { label: "Automotive help", value: "Automotive help" },
            { label: "Handyman", value: "Handyman" },
            { label: "Lawn care services", value: "Lawn care services" },
            { label: "Gutter cleaning", value: "Gutter cleaning" },
            { label: "Tree trimming service", value: "Tree trimming service" },
            { label: "Vacation plant watering", value: "Vacation plant watering" },
            { label: "Patio cleaning", value: "Patio cleaning" },
            { label: "Hot tub cleaning", value: "Hot tub cleaning" },
            { label: "Deck restoration services", value: "Deck restoration services" },
            { label: "Patio furniture assembly", value: "Patio furniture assembly" },
            { label: "Fence staining", value: "Fence staining" },
            { label: "Mulching services", value: "Mulching services" },
            { label: "Lawn fertilizer service", value: "Lawn fertilizer service" },
            { label: "Hedge trimming service", value: "Hedge trimming service" },
            { label: "Outdoor party setup", value: "Outdoor party setup" },
            { label: "Urban gardening service", value: "Urban gardening service" },
            { label: "Leaf raking and removal", value: "Leaf raking and removal" },
            { label: "Produce gardening", value: "Produce gardening" },
            { label: "Pressure washing", value: "Pressure washing" },
            { label: "House help", value: "House help" },
            { label: "Driver", value: "Driver" },
            { label: "Cook", value: "Cook" },
            { label: "General cleaning", value: "General cleaning" },
            { label: "Personal assistant", value: "Personal assistant" },
            { label: "Yard work", value: "Yard work" },
            { label: "Home organization", value: "Home organization" },
            { label: "Pet grooming", value: "Pet grooming" },
            { label: "Laundry and ironing", value: "Laundry and ironing" },
            { label: "Personal shopping and styling", value: "Personal shopping and styling" },
            { label: "Car washing", value: "Car washing" },
            { label: "Face painting", value: "Face painting" },

        ]
    },
    {
        categoryName: 'Event and Outdoor Services',
        subCatory: [
            { label: "Delivery", value: "Delivery" },
            { label: "Organization", value: "Organization" },
            { label: "Furniture assembly", value: "Furniture assembly" },
            { label: "Moving and packing", value: "Moving and packing" },
            { label: "Wait in line", value: "Wait in line" },
            { label: "Organize closet", value: "Organize closet" },
            { label: "Personal shopping and errands", value: "Personal shopping and errands" },
            { label: "Gift wrapping services", value: "Gift wrapping services" },
            { label: "Hang Christmas lights", value: "Hang Christmas lights" },
            { label: "Christmas tree delivery", value: "Christmas tree delivery" },
            { label: "Holiday decorating", value: "Holiday decorating" },
            { label: "Party cleaning", value: "Party cleaning" },
            { label: "Holiday tree decorators", value: "Holiday tree decorators" },
            { label: "Toy assembly service", value: "Toy assembly service" },
            { label: "Christmas tree removal", value: "Christmas tree removal" },

        ]

    },
    {
        categoryName: 'Event Planning and Renter Services',
        subCatory: [
            { label: "Tent rentals", value: "Tent rentals" },
            { label: "Event catering", value: "Event catering" },
            { label: "Event photography", value: "Event photography" },
            { label: "Event videography", value: "Event videography" },
            { label: "Live music", value: "Live music" },
            { label: "Printing and publishing", value: "Printing and publishing" },
            { label: "Event staffing", value: "Event staffing" },
            { label: "Event planning and coordination", value: "Event planning and coordination" },
            { label: "Party planning and entertainment", value: "Party planning and entertainment" },
            { label: "DJ services", value: "DJ services" },
            { label: "Musicians and live entertainment", value: "Musicians and live entertainment" },
            { label: "Photographers", value: "Photographers" },
            { label: "Videographers", value: "Videographers" },
            { label: "Voice actors", value: "Voice actors" },
            { label: "Screenwriting and scriptwriting", value: "Screenwriting and scriptwriting" },
            { label: "Playwriting and theater production", value: "Playwriting and theater production" },
            { label: "Comedy writing and performance", value: "Comedy writing and performance" },
            { label: "Magic and illusion show", value: "Magic and illusion show" },
            { label: "Escape rooms", value: "Escape rooms" },
            { label: "Scavenger hunts", value: "Scavenger hunts" },
            { label: "Murder mystery events", value: "Murder mystery events" },
            { label: "Game shows", value: "Game shows" },
            { label: "Trivia nights", value: "Trivia nights" },
            { label: "Karaoke services", value: "Karaoke services" },
            { label: "Movie and TV trivia", value: "Movie and TV trivia" },
            { label: "Stand-up comedy shows", value: "Stand-up comedy shows" },
            { label: "Improve performances", value: "Improve performances" },
            { label: "Psychic readings and tarot card readings", value: "Psychic readings and tarot card readings" },
            { label: "Astrology and palm reading", value: "Astrology and palm reading" },
            { label: "Henna tattoo", value: "Henna tattoo" },
            { label: "Balloon twisting", value: "Balloon twisting" },
            { label: "Caricature drawing", value: "Caricature drawing" },
            { label: "Magic shows", value: "Magic shows" },
            { label: "Clowns", value: "Clowns" },
            { label: "Puppet shows", value: "Puppet shows" },
            { label: "Jugglers", value: "Jugglers" },
            { label: "Stilt walkers", value: "Stilt walkers" },
            { label: "Fire eating", value: "Fire eating" },
            { label: "Fire breathing", value: "Fire breathing" },
        ]
    },
    {
        categoryName: 'Office and Business Services',
        subCatory: [
            { label: "Office cleaning", value: "Office cleaning" },
            { label: "Office tech setup", value: "Office tech setup" },
            { label: "Office movers", value: "Office movers" },
            { label: "Office supply and snack delivery", value: "Office supply and snack delivery" },
            { label: "Office furniture assembly", value: "Office furniture assembly" },
            { label: "Office setup and organization", value: "Office setup and organization" },
            { label: "Office administration", value: "Office administration" },
            { label: "Office interior design", value: "Office interior design" },
            { label: "Moving office furniture", value: "Moving office furniture" },
            { label: "Office mounting service", value: "Office mounting service" },
            { label: "Search engine optimization (SEO)", value: "Search engine optimization (SEO)" },
            { label: "Social media management", value: "Social media management" },
            { label: "Online advertising", value: "Online advertising" },
            { label: "Content creation", value: "Content creation" },
            { label: "E-commerce and online store management", value: "E-commerce and online store management" },
            { label: "Data entry and database management", value: "Data entry and database management" },
            { label: "Customer service and support", value: "Customer service and support" },
            { label: "Translation services", value: "Translation services" },
            { label: "Online tutoring and education", value: "Online tutoring and education" },
            { label: "Video production and editing", value: "Video production and editing" },
            { label: "Online event planning and coordination", value: "Online event planning and coordination" },
            { label: "Online therapy and counseling", value: "Online therapy and counseling" },
            { label: "Legal Service", value: "Legal Service" },
            { label: "Business Consultancy Service", value: "Business Consultancy Service" },
            { label: "Information Technology Consultancy Service", value: "Information Technology Consultancy Service" },

        ]
    },
    {
        categoryName: 'Education and Tutoring Services',
        subCatory: [
            { label: "Home tutor", value: "Home tutor" },
            { label: "Test preparation (e.g., SAT, ACT, GMAT)", value: "Test preparation (e.g., SAT, ACT, GMAT)" },
            { label: "Language learning services", value: "Language learning services" },
            { label: "Business plan writing", value: "Business plan writing" },
            { label: "Investment consulting", value: "Investment consulting" },
            { label: "Financial planning", value: "Financial planning" },
            { label: "Insurance consulting", value: "Insurance consulting" },
            { label: "Real estate consulting", value: "Real estate consulting" },
            { label: "Tutoring and homework help", value: "Tutoring and homework help" },
            { label: "Music lessons", value: "Music lessons" },
            { label: "Art lessons", value: "Art lessons" },
            { label: "Dance lessons", value: "Dance lessons" },
            { label: "Cooking lessons", value: "Cooking lessons" },

        ]
    },
    {
        categoryName: 'Health and Wellness Services',
        subCatory: [
            { label: "Personal training and fitness coaching", value: "Personal training and fitness coaching" },
            { label: "Nutrition consulting", value: "Nutrition consulting" },
            { label: "Massage therapy", value: "Massage therapy" },
            { label: "Beauty and personal grooming services", value: "Beauty and personal grooming services" },
            { label: "Pet sitting and dog walking", value: "Pet sitting and dog walking" },
            { label: "Baby sitting and child care", value: "Baby sitting and child care" },
            { label: "Senior/Elderly care", value: "Senior/Elderly care" },

        ]
    },
    {
        categoryName: 'Legal and Professional Services',
        subCatory: [
            { label: "Legal services", value: "Legal services" },
            { label: "Marketing and market research", value: "Marketing and market research" },
            { label: "Project management", value: "Project management" },
            { label: "Financial consulting and bookkeeping", value: "Financial consulting and bookkeeping" },
            { label: "Resume writing and career coaching", value: "Resume writing and career coaching" },
            { label: "Graphic design", value: "Graphic design" },
            { label: "Photo and video editing", value: "Photo and video editing" },
            { label: "Voiceover work", value: "Voiceover work" },
            { label: "Translation and interpretation services", value: "Translation and interpretation services" },

        ]
    },
    {
        categoryName: 'Home Improvement Services',
        subCatory: [
            { label: "Interior design", value: "Interior design" },
            { label: "Landscaping, lawn care and garden design", value: "Landscaping, lawn care and garden design" },
            { label: "Architecture and home design", value: "Architecture and home design" },
            { label: "HVAC services", value: "HVAC services" },
            { label: "Housekeeping and cleaning ", value: "Housekeeping and cleaning " },
            { label: "Home brewing and winemaking services", value: "Home brewing and winemaking services" },
            { label: "Gardening and farming services", value: "Gardening and farming services" },
            { label: "Wedding planning and coordination", value: "Wedding planning and coordination" },
            { label: "Real estate agent", value: "Real estate agent" },

        ]
    },
    {
        categoryName: 'Personal Services',
        subCatory: [
            { label: "Personal assistant", value: "Personal assistant" },
            { label: "Research assistant", value: "Research assistant" },
            { label: "Virtual assistant", value: "Virtual assistant" },
            { label: "Help cooking and serving food", value: "Help cooking and serving food" },
            { label: "Shop for and install decorations", value: "Shop for and install decorations" },
            { label: "Entertain guests", value: "Entertain guests" },
            { label: "Event help and wait staff", value: "Event help and wait staff" },
            { label: "Event decorating", value: "Event decorating" },
            { label: "Event staffing", value: "Event staffing" },
            { label: "Birthday and party planning", value: "Birthday and party planning" },
            { label: "Event marketing", value: "Event marketing" },

        ]
    },
    {
        categoryName: 'Home Improvement Services',
        subCatory: [
            { label: "Security service", value: "Security service" },
            { label: "Office cleaning", value: "Office cleaning" },
            { label: "Office tech setup", value: "Office tech setup" },
            { label: "Office movers", value: "Office movers" },
            { label: "Office supply and snack delivery", value: "Office supply and snack delivery" },
            { label: "Office furniture assembly", value: "Office furniture assembly" },
            { label: "Office setup and organization", value: "Office setup and organization" },
            { label: "Office administration", value: "Office administration" },
            { label: "Office interior design", value: "Office interior design" },
            { label: "Moving office furniture", value: "Moving office furniture" },
            { label: "Office mounting service", value: "Office mounting service" },

        ]
    }
]
